### ISSUE TITLE
Parameterize C extension 

### ISSUE THREAD

**Issue by usmnzain** [merledu/nucleusrv#50]
- [x] C ext flag

**Comment by Talha-Ahmed-1** [comment]
It is dependent on compliance update.

**Comment by Talha-Ahmed-1** [comment]
https://github.com/PacoReinaCampo/PU-RISCV will be helpful in implementation of rv64

**Comment by usmnzain** [comment]
https://github.com/merledu/nucleusrv/pull/53 solves this issue.
